export const EXPO_PUBLIC_PUBNUB_PUBLISH_KEY = process.env.EXPO_PUBLIC_PUBNUB_PUBLISH_KEY;
export const EXPO_PUBLIC_PUBNUB_SUBSCRIBE_KEY = process.env.EXPO_PUBLIC_PUBNUB_SUBSCRIBE_KEY;

const pubnubConfig = {
  EXPO_PUBLIC_PUBNUB_PUBLISH_KEY,
  EXPO_PUBLIC_PUBNUB_SUBSCRIBE_KEY,
};

export default pubnubConfig;
